import { file_exists } from "std/fs"
import { info, fatal } from "../../lib/utils.ab"
import { get_project_amber, require_project, get_ini_value } from "../../lib/project.ab"
import { get_amethyst_data_dir } from "../../lib/environment.ab"
import { relative } from "../../lib/path.ab"

pub fun cmd_build(arguments: [Text]): Null {
    const project = require_project()

    const name = get_ini_value("project", "name")

    let entry = get_ini_value("project", "entry")
    if entry == "" {
        fatal("This project doesn't have a configured entry point, please specify one in your amethyst.ini")
    }

    entry = relative("{project}/{entry}")
    if not file_exists(entry) {
        fatal("{entry} does not exist")
    }

    const target = "{project}/target"
    trust $ rm -rf "{target}" && mkdir -p "{target}" $

    const data_dir = get_amethyst_data_dir()
    const version = get_project_amber()
    let amber = ""

    if version == "system" {
        amber = "amber"
    } else {
        amber = "{data_dir}/amber/amber.{version}.bin"
    }
    trust $ exec "{amber}" build "{entry}" "{target}/{name}.sh" $

    exit(0)
}
